// Generated by LiveScript 1.2.0
var ref$, each, listsToObj, take, drop, reverse, first, flatten;
ref$ = require("prelude-ls"), each = ref$.each, listsToObj = ref$.listsToObj, take = ref$.take, drop = ref$.drop, reverse = ref$.reverse, first = ref$.first, flatten = ref$.flatten;
d3.json("../week_hour_total/station_start.json", function(err, startJson){
  var enddate, at;
  enddate = new Date("Fri May 09 2014 08:22:54 GMT+0800 (CST)");
  for (at in startJson) {
    startJson[at] = (enddate - new Date(startJson[at])) / 1000 / 60;
  }
  return console.log(startJson);
});