// Generated by LiveScript 1.2.0
var each, svg, line;
each = require("prelude-ls").each;
svg = d3.select(".svgctnr").append("svg").attr({
  "width": 700,
  "height": 800
}).style({
  "position": "fixed",
  "left": 700,
  "top": 250
}).append("g");
line = d3.svg.line().interpolate("basis").x(function(it, i){
  return i * 30;
}).y(function(it, i){
  return it;
});
svg.selectAll("path").data([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20].map(function(){
  return Math.random() * 500;
})]).enter().append("path").style({
  "fill": "none",
  "stroke-width": 5,
  "stroke": "orange"
}).attr({
  "d": function(){
    return line([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20].map(function(){
      return 600;
    }));
  }
}).transition().duration(1000).attr({
  "d": function(it){
    return line(it);
  }
});